name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:

    # Upload Artifacts
    - name: Upload Build Artifact
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ secrets.GITHUB_REPOSITORY }}
      uses: actions/upload-artifact@v2
      with:
        name: KoalaLauncher-win32
        path: D:\a\${{env.GH_REPO}}\deploy