name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_OWNER: "TOLoneWolf"
        GH_REPO: "test-compile"

    steps:

    # Upload Artifacts
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: KoalaLauncher-win32
        path: D:\a\${{ env.GH_OWNER }}\${{ env.GH_REPO }}\deploy
