name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_OWNER: "TOLoneWolf"
      GH_REPO: "test-compile"

    steps:

    # Checkout Code
    - uses: actions/checkout@v2

    # - uses: c-hive/gha-npm-cache@v1

    - uses: egordm/gha-yarn-node-cache@v1

    # - name: Setup VS2019
    #   uses: warrenbuckley/Setup-MSBuild@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      # with:
      #   vs-version: '[16.*]'
    
    # https://github.com/marketplace/actions/setup-python
    - name: Set Python Version
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        # architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    # - name: MSBuild
    #   working-directory: src
    #   run: msbuild MyProject.csproj

    # Set Node Version
    - name: Set Node Version
      uses: actions/setup-node@v1
      with:
        node-version: '14.8.0'

    # Set Python Version
    - name: Set Python Version
      run: npm config set python python2.7

    # # Install Node Tools
    # - name: Install Node Tools
    #   run: npm install --global --production --vs2015 windows-build-tools@4.0.0

    # Install Node GYP
    - name: Install Node GYP
      run: npm install --global node-gyp@latest

    # Set Node MSVC Version
    - name: Set Node MSVC Version
      run: npm config set msvs_version 2019

    # Increase Yarn Timeout due to Azure Timing It Out
    - name: Increase Yarn Timeout
      run: yarn --network-timeout 100000

    # Fetch Dependencies
    - name: Fetch Dependencies
      run: yarn

    # Build Launcher
    - name: Build Launcher
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TESTING: true
      run: yarn release

    # Upload Release if Needed
    - name: Upload Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn upload
      
    # Upload Artifacts
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: KoalaLauncher-win32
        path: D:\a\${{ env.GH_OWNER }}\${{ env.GH_REPO }}\deploy

    # Send Webhook Notification
    - uses: actions/setup-ruby@v1
    - name: Send Webhook Notification
      env:
        JOB_STATUS: ${{ job.status }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        HOOK_OS_NAME: ${{ runner.os }}
        WORKFLOW_NAME: ${{ github.workflow }}
      run: |
        git clone https://github.com/KoalaDevs/github-actions-discord-webhook.git webhook
        bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
      shell: bash